services:
  app:
    build:
      context: .
      dockerfile: ./app/Dockerfile
    container_name: cp-fastapi
  db:
    image: postgres:17.5
    container_name: cp-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: cp_database
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./db/init:/docker-entrypoint-initdb.d
volumes:
  pgdata: